### ISSUE TITLE
CALL can take additional parameters

### ISSUE THREAD

**Issue by michaeljon** [dfgordon/tree-sitter-applesoft#1]
This is a valid Applesoft program. The tokenizer / verifier considers the CALL statement invalid. Detokenizing the file pulled from disk produces the correct BASIC code. This is decidedly a corner case and isn't called out in the Applesoft manuals that I can see. Examples are in chapters 16 and 17 of Assembly Lines https://archive.org/download/AssemblyLinesCompleteWagner/AssemblyLinesCompleteWagner.pdf

```
200 I = 100
210 FOR I = 0 TO 100
220 CALL 768,I,I
230 NEXT I
```

Trying to verify or tokenize this using `a2kit get -f foo.A | a2kit verify -t atxt` results in:

```
ERROR row 2 col 8
    220 CALL 768,I,I
Error: Syntax
```

```
0801 : 0B 08 C8 00 49 D0 31 30 30 00 18 08 D2 00 81 49 |+| ....I.100......I |-| ..H..P......R...
0811 : D0 30 C1 31 30 30 00 25 08 DC 00 8C 37 36 38 2C |+| .0.100.%....768, |-| P.A......\......
0821 : 49 2C 49 00 2C 08 E6 00 82 49 00 00 00 0A       |+| I,I.,....I....   |-| ......f.......
```

**Comment by dfgordon** [comment]
Thanks for this example, I was not aware of it, but I have thought about similar cases.  An important thing to realize is this depends on the called routine to do the "extra parsing."  That is, the interpreter doesn't (directly) parse the `,I,I`.  Whoever wrote the code at address 768 does that.  It is much like an ampersand command. 

The difficulty for a parser is that the syntax following the address is arbitrary, i.e., assembly programmers can make up whatever syntax they want.

I can think of a few courses one might take:
* consider it an edge case and do nothing
* support comma delimited expressions like in the example
* treat `CALL` and `&` using the same parsing rules (`&` also has difficulties)
* try to allow for something very arbitrary - but this begins to defeat the purpose of a language server

**Comment by dfgordon** [comment]
Version 3.2 accepts comma delimited expressions after CALL.  N.b. this will not propagate downstream immediately, and when it does will likely be controlled by settings or options.
